- name: nginx up to date
  become: true
  apt:
    name: nginx
    state: latest
- name: base nginx config
  become: true
  template:
    src: ./templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - restart nginx

